// frontend/src/components/TableNode.vue
<script setup lang="ts">
import { Handle, Position } from "@vue-flow/core";
import { Key } from "lucide-vue-next";

const props = defineProps<{
  id: string;
  data: {
    name: string;
    label?: string;
    headerColor?: string;
    columns: Array<{
      name: string;
      type: string;
      is_pk: boolean;
      is_fk: boolean;
    }>;
  };
  selected?: boolean;
}>();

const getTypeColor = (type: string) => {
  const t = type.toLowerCase();
  if (t.includes("int")) return "text-blue-500";
  if (t.includes("char") || t.includes("text")) return "text-emerald-500";
  if (t.includes("date") || t.includes("time") || t.includes("stamp"))
    return "text-orange-500";
  if (t.includes("bool") || t.includes("json")) return "text-purple-500";
  return "text-gray-400";
};
</script>

<template>
  <div
    class="bg-white rounded-xl shadow-lg border-2 min-w-[200px] overflow-hidden transition-all duration-300 group"
    :class="
      selected
        ? 'border-blue-500 ring-4 ring-blue-50/50 scale-[1.02]'
        : 'border-gray-200 hover:border-blue-300'
    "
  >
    <!-- Header -->
    <div
      class="px-4 py-3 border-b flex items-center justify-between"
      :style="{
        backgroundColor: data.headerColor || '#ffffff',
        borderColor: selected ? '#3b82f6' : '#e2e8f0',
      }"
    >
      <div class="flex flex-col">
        <span
          class="text-[10px] uppercase font-black tracking-widest text-gray-400 leading-none mb-1"
          >Table</span
        >
        <span
          class="text-sm font-bold text-gray-900 truncate max-w-[150px] uppercase"
          >{{ data.name || data.label }}</span
        >
      </div>
    </div>

    <!-- Column List -->
    <div class="py-1 bg-white">
      <div
        v-for="(col, index) in data.columns"
        :key="index"
        class="relative flex justify-between items-center py-1.5 px-4 hover:bg-blue-50/50 transition-colors group/col"
      >
        <!-- Target Handle (Left) -->
        <Handle
          :id="`target-${col.name}`"
          type="target"
          :position="Position.Left"
          class="!w-2 !h-2 !bg-blue-400 !border-none !-left-1 opacity-0 group-hover/col:opacity-100 transition-all"
        />

        <div class="flex items-center gap-2 flex-1 min-w-0">
          <!-- PK Icon -->
          <div class="w-4 flex-shrink-0">
            <Key
              v-if="col.is_pk"
              class="w-3.5 h-3.5 text-amber-500 fill-amber-500"
            />
            <Key
              v-else-if="col.is_fk"
              class="w-3 h-3 text-gray-300 -rotate-45"
            />
          </div>

          <span
            class="text-[12px] font-medium truncate"
            :class="col.is_pk ? 'text-gray-900 font-bold' : 'text-gray-600'"
          >
            {{ col.name }}
          </span>
        </div>

        <span
          class="text-[10px] ml-4 font-mono font-bold uppercase shrink-0 opacity-70"
          :class="getTypeColor(col.type)"
        >
          {{ col.type }}
        </span>

        <!-- Source Handle (Right) -->
        <Handle
          :id="`source-${col.name}`"
          type="source"
          :position="Position.Right"
          class="!w-2 !h-2 !bg-blue-600 !border-none !-right-1 opacity-0 group-hover/col:opacity-100 transition-all"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
.vue-flow__handle:hover {
  transform: scale(1.5);
  background: #2563eb !important;
}
</style>

// frontend/src/components/canvas/TableNode.tsx
'use client';

import { Handle, Position } from '@xyflow/react';
import { Table as TableIcon, Key } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function TableNode({ data, selected }: { data: any, selected: boolean }) {
  const { name, columns } = data;

  return (
    <div className={cn(
      "min-w-[240px] bg-white rounded-xl shadow-2xl border-2 transition-all duration-200 overflow-hidden",
      selected ? "border-blue-500 scale-[1.02] ring-4 ring-blue-500/10" : "border-slate-200"
    )}>
      {/* Table Header */}
      <div className={cn(
        "px-4 py-3 border-b flex items-center gap-2.5",
        selected ? "bg-blue-600 border-blue-600" : "bg-slate-50 border-slate-200"
      )}>
        <TableIcon className={cn("w-4 h-4", selected ? "text-white" : "text-slate-400")} />
        <span className={cn("text-xs font-black uppercase tracking-wider", selected ? "text-white" : "text-slate-700")}>
          {name}
        </span>
      </div>

      {/* Columns List */}
      <div className="py-1">
        {columns?.map((col: any, idx: number) => (
          <div key={idx} className="group relative flex items-center px-4 py-2 hover:bg-slate-50 transition-colors">
            {/* Left Handle (Target) */}
            <Handle
              type="target"
              position={Position.Left}
              id={`${name}-${col.name}-left`}
              className="!w-2 !h-2 !bg-blue-400 !border-2 !border-white !opacity-0 group-hover:!opacity-100 transition-opacity"
            />

            <div className="flex-1 flex items-center justify-between gap-4">
              <div className="flex items-center gap-2">
                {col.is_pk ? (
                  <Key className="w-3 h-3 text-amber-500 fill-amber-500" />
                ) : (
                  <div className="w-3" /> 
                )}
                <span className="text-[11px] font-bold text-slate-700 truncate max-w-[120px]">
                    {col.name}
                </span>
              </div>
              
              <div className="flex items-center justify-end gap-1.5 min-w-fit">
                 <span className="text-[9px] font-black text-slate-400 uppercase tracking-tighter bg-slate-100 px-1.5 py-0.5 rounded leading-none">
                    {col.type}
                 </span>
                 {col.nullable && (
                   <span className="text-[10px] font-bold text-blue-400 leading-none">?</span>
                 )}
                 {col.is_ai && (
                   <span className="text-[9px] font-black text-emerald-500 leading-none">AI</span>
                 )}
              </div>
            </div>

            {/* Right Handle (Source) */}
            <Handle
              type="source"
              position={Position.Right}
              id={`${name}-${col.name}-right`}
              className="!w-2 !h-2 !bg-blue-400 !border-2 !border-white !opacity-0 group-hover:!opacity-100 transition-opacity"
            />
          </div>
        ))}
      </div>
      
      {/* Footer Info */}
      <div className="px-4 py-1.5 bg-slate-50/50 border-t border-slate-100 flex justify-between items-center">
         <span className="text-[8px] font-bold text-slate-300 uppercase tracking-widest">
           InnodB
         </span>
         <span className="text-[8px] font-bold text-slate-400">
           {columns?.length || 0} COLS
         </span>
      </div>
    </div>
  );
}
