// frontend/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import TheNavbar from "./components/layout/TheNavbar.vue";
import TheSidebar from "./components/layout/TheSidebar.vue";
import ERDCanvas from "./components/layout/ERDCanvas.vue";
import SQLEditor from "./components/pages/SQLEditor.vue";
import DataBrowser from "./components/pages/DataBrowser.vue";
import UserManagement from "./components/pages/admin/UserManagement.vue";
import DataDrawer from "./components/layout/DataDrawer.vue";
import ContextPanel from "./components/layout/ContextPanel.vue";
import ToastContainer from "./components/ui/ToastContainer.vue";
import { useSchema } from "./composables/useSchema";

const { currentDatabase } = useSchema();
const isDataDrawerOpen = ref(false);
const selectedTableForData = ref("");
const selectedNodeData = ref<any>(null);
const selectedDatabase = ref<string>("");
const selectionTimestamp = ref(0);
const activePage = ref("diagram");

const handleTableSelect = (tableName: string) => {
  selectedTableForData.value = tableName;
  selectedDatabase.value = "";
  selectedNodeData.value = null;

  if (activePage.value === "diagram") {
    isDataDrawerOpen.value = true;
  } else {
    activePage.value = "data";
  }
};

const handleDatabaseSelect = (dbName: string) => {
  selectedDatabase.value = dbName;
  currentDatabase.value = dbName;
  selectedTableForData.value = "";
  selectedNodeData.value = null;
  selectionTimestamp.value = Date.now();
};

const handleNodeSelect = (node: any) => {
  if (!node) {
    selectedNodeData.value = null;
    return;
  }
  selectedNodeData.value = node;
  selectionTimestamp.value = Date.now();
};

const handleNavigation = (page: string) => {
  activePage.value = page;
};

// Compute context panel type
const panelType = computed(() => {
  if (selectedNodeData.value) {
    const t = selectedNodeData.value.type;
    if (t === "note") return "note-edit";
    if (t === "group") return "group-edit";
    return "table-edit";
  }
  if (selectedDatabase.value) return "database";
  return "none";
});

const showRightPanel = computed(() => activePage.value === 'diagram' && (selectedNodeData.value || selectedDatabase.value));
</script>

<template>
  <div class="h-screen w-screen flex flex-col overflow-hidden bg-white">
    <!-- Navbar (Fixed Top) -->
    <TheNavbar :current-page="activePage" @navigate="handleNavigation" class="shrink-0 z-50 border-b border-gray-200" />

    <div class="flex-1 flex overflow-hidden relative">
      <!-- 1. LEFT SIDEBAR (Explorer) -->
      <aside class="w-[280px] shrink-0 border-r border-gray-200 flex flex-col bg-[#f8fafc] z-20">
        <TheSidebar
          @select-table="handleTableSelect"
          @select-database="handleDatabaseSelect"
          @navigate="handleNavigation"
          class="flex-1 overflow-y-auto scrollbar-thin"
        />
      </aside>

      <!-- 2. MAIN CENTER AREA (Editor + Bottom Panel) -->
      <main class="flex-1 flex flex-col overflow-hidden relative bg-slate-100 z-10">
        <!-- TOP EDITOR REGION -->
        <div class="flex-1 relative overflow-hidden flex flex-col">
            <Transition name="page" mode="out-in">
                <!-- CANVAS PAGE -->
                <div v-if="activePage === 'diagram'" class="h-full w-full flex flex-col relative">
                    <ERDCanvas
                        :active-database="currentDatabase"
                        @node-select="handleNodeSelect"
                        class="flex-1"
                    />
                </div>

                <!-- OTHER PAGES -->
                <div v-else-if="activePage === 'sql'" class="h-full w-full bg-white p-6 overflow-auto">
                    <SQLEditor />
                </div>
                <div v-else-if="activePage === 'data'" class="h-full w-full bg-white p-4 overflow-auto">
                    <DataBrowser :table-name="selectedTableForData" />
                </div>
                <div v-else-if="activePage === 'admin-users'" class="h-full w-full bg-white overflow-auto">
                    <UserManagement />
                </div>
                <div v-else class="h-full flex items-center justify-center text-gray-400">
                    <p class="text-sm font-bold uppercase tracking-widest opacity-30">Module Preparation</p>
                </div>
            </Transition>
        </div>

        <!-- BOTTOM PANEL (Data Drawer) - SELEVEL DENGAN SIDEBAR DALAM MAIN COLUMN -->
        <DataDrawer
            v-if="activePage === 'diagram' && isDataDrawerOpen"
            :is-open="isDataDrawerOpen"
            :table-name="selectedTableForData"
            @close="isDataDrawerOpen = false"
            class="shrink-0"
        />
      </main>

      <!-- 3. RIGHT SIDEBAR (Properties) -->
      <aside 
        v-if="showRightPanel"
        class="w-[340px] shrink-0 border-l border-gray-200 bg-white z-20 flex flex-col overflow-hidden"
      >
        <ContextPanel
          :trigger="selectionTimestamp"
          :active-database="selectedDatabase"
          :type="panelType as any"
          :data="selectedNodeData"
          class="flex-1"
        />
      </aside>
    </div>

    <!-- Modals & Toasts -->
    <ToastContainer />
  </div>
</template>

<style>
/* Smooth transitions */
.page-enter-active, .page-leave-active {
  transition: opacity 0.2s ease;
}
.page-enter-from, .page-leave-to {
  opacity: 0;
}

.scrollbar-thin::-webkit-scrollbar {
  width: 4px;
}
.scrollbar-thin::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 10px;
}
</style>

// frontend/src/app/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Navbar from '@/components/layout/Navbar';
import Sidebar from '@/components/layout/Sidebar';
import ConnectionModal from '@/components/modals/ConnectionModal';
import { useConnectionStore } from '@/store/useConnectionStore';
import { useSchemaStore } from '@/store/useSchemaStore';
import { Database, Plus } from 'lucide-react';

import ERDCanvas from '@/components/canvas/ERDCanvas';

export default function Home() {
  const [activePage, setActivePage] = useState<'diagram' | 'data' | 'sql'>('diagram');
  const [isConnModalOpen, setIsConnModalOpen] = useState(false);
  const { activeConnection } = useConnectionStore();
  const { currentDatabase } = useSchemaStore();

  // Open modal on load if no active connection (optional UX)
  useEffect(() => {
    if (!activeConnection) {
        setIsConnModalOpen(true);
    }
  }, [activeConnection]);

  return (
    <div className="flex flex-col h-screen w-full bg-white overflow-hidden text-slate-900">
      {/* 1. TOP NAV */}
      <Navbar activePage={activePage} onNavigate={setActivePage} />

      {/* 2. MAIN WORKSPACE */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left Sidebar */}
        <Sidebar />

        {/* Center Canvas / Content Area */}
        <div className="flex-1 relative bg-slate-50 flex flex-col overflow-hidden">
          {/* Active Database Content Area */}
          {!currentDatabase ? (
            <div className="flex-1 flex flex-col items-center justify-center p-12 text-center">
              <div className="w-20 h-20 bg-blue-100 rounded-3xl flex items-center justify-center mb-6">
                <Database className="w-10 h-10 text-blue-600" />
              </div>
              <h3 className="text-xl font-bold text-slate-800">No Database Active</h3>
              <p className="text-slate-500 max-w-sm mt-2">
                Select a database from the sidebar or create a new one to start architecting your schema.
              </p>
              <div className="mt-8 flex gap-4">
                <button className="px-6 py-2.5 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-200 flex items-center gap-2">
                  <Plus className="w-4 h-4" /> New Table
                </button>
                <button 
                  onClick={() => setIsConnModalOpen(true)}
                  className="px-6 py-2.5 bg-white border border-slate-200 text-slate-600 rounded-xl font-bold hover:bg-slate-50 transition-all"
                >
                  Change Connection
                </button>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col overflow-hidden">
                {activePage === 'diagram' && <ERDCanvas />}
                {activePage === 'data' && (
                    <div className="flex-1 flex items-center justify-center p-12 text-slate-400">
                        Data Browser Coming Soon...
                    </div>
                )}
                {activePage === 'sql' && (
                    <div className="flex-1 flex items-center justify-center p-12 text-slate-400">
                        SQL Console Coming Soon...
                    </div>
                )}
            </div>
          )}

          {/* Bottom Bar (Statistics placeholder) */}
          <div className="h-7 bg-white border-t border-slate-200 flex items-center px-4 justify-between shrink-0">
             <div className="flex items-center gap-4 text-[10px] uppercase font-bold tracking-widest text-slate-400">
                <span className="flex items-center gap-1.5"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> System Ready</span>
                <span>InnoDB Engine</span>
             </div>
             <div className="text-[10px] font-mono text-slate-400">
                UTF8MB4_UNICODE_CI
             </div>
          </div>
        </div>

        {/* 3. Right Property Panel (To be implemented) */}
        <aside className="w-[300px] border-l border-slate-200 bg-white hidden lg:flex flex-col">
           <div className="p-4 border-b border-slate-200">
             <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Properties</h3>
           </div>
           <div className="flex-1 flex items-center justify-center p-8 text-center">
              <p className="text-xs text-slate-300 italic italic">No item selected</p>
           </div>
        </aside>
      </div>

      {/* Modals */}
      <ConnectionModal 
        isOpen={isConnModalOpen} 
        onClose={() => setIsConnModalOpen(false)} 
        onConnect={() => console.log("Re-connected")} 
      />
    </div>
  );
}
